<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3fd99949-eaec-44f1-8e69-16efa3bc011f</testSuiteGuid>
   <testCaseLink>
      <guid>50d4cd07-fd02-4eab-beb5-b6426f8d6343</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC1</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b48c177-b5fd-491f-8bd5-7c1418e77ec8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f29416eb-0c87-4631-928b-ed9be2e1f7bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5dabf523-a8fc-41ba-b0e8-c7aec74bd106</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>adab6d67-06ed-451a-bbbb-ccec85d85d4d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC2</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c52e94db-0160-4ff6-8b9b-b9af0649d932</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a765f296-6ad4-41f9-b6ab-c624f6adb010</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0394db2f-1fbb-42e0-a92e-51e7ca76e8cb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>76c7d57f-305a-44a0-b762-91016749d47d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC3</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>021ffdff-575e-4592-a584-a3fa0eb9d30d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51824efb-509e-47fb-9d9f-6efe6a196593</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8f89810-68a1-47b6-971d-5903f3199644</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>22bf94f0-0418-43cb-9f00-c9980103fd69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC4</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea49852a-ab4f-4d75-b8c4-5380638120d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>464d51e3-feef-453b-943d-17d45bc5f1f3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>804d3f0f-30ef-47d3-9bac-34ecd0f22681</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC5</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3cfa70b-828d-4742-87c8-9b76bfe2d5e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc5b0615-c0fd-45b2-9395-ee5367531e3d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
